### ISSUE TITLE
electron-webpack is looking for src/render/index

### ISSUE THREAD

**Issue by eshimischi** [antfu/icones#13]
`> icones-electron@0.0.0 compile /Users/****/WWW/icones/electron
> electron-webpack

Error: Cannot find entry file src/renderer/index.ts (or main.ts, or app.ts, or index.js, or main.js, or app.js)
    at computeEntryFile (/Users/****/WWW/icones/node_modules/.pnpm/electron-webpack@2.8.2_webpack@4.44.1/node_modules/electron-webpack/src/main.ts:389:11)
    at WebpackConfigurator.configure (/Users/****/WWW/icones/node_modules/.pnpm/electron-webpack@2.8.2_webpack@4.44.1/node_modules/electron-webpack/src/main.ts:222:29)
    at configure (/Users/****/WWW/icones/node_modules/.pnpm/electron-webpack@2.8.2_webpack@4.44.1/node_modules/electron-webpack/src/main.ts:376:10)
 ERROR  Command failed with exit code 1.`

**Comment by antfu** [comment]
Just create an empty `index.js` in render would make it work. I am still working on it though. We don't actually need the render function, `electron-builder` doesn't allow it to be empty but ok if the file doesn't exist, while `electron-webpack` requires this file but allowing to be empty... 😂 Will try to find a solution.

**Comment by eshimischi** [comment]
Thanks, yes indeed i thought about an empty file, but .. your word is first :)
